version: '3.8'

x-common-variables: &common-variables
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1002}
  TZ: ${TZ:-UTC}

networks:
  jarvis-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16

services:
  # ============= Infrastructure Services =============
  
  postgres:
    image: pgvector/pgvector:pg16
    container_name: jarvis-postgres
    hostname: postgres
    user: "999:${PGID:-1002}"
    environment:
      <<: *common-variables
      POSTGRES_DB: ${POSTGRES_DB:-jarvis}
      POSTGRES_USER: ${POSTGRES_USER:-jarvis}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jarvis123}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - /mnt/appsdata/jarvis/postgres:/var/lib/postgresql/data
      - /mnt/appsdata/jarvis/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      jarvis-network:
        aliases:
          - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jarvis"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: jarvis-redis
    hostname: redis
    user: "999:${PGID:-1002}"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --dir /data
    ports:
      - "6379:6379"
    volumes:
      - /mnt/appsdata/jarvis/redis:/data
    networks:
      jarvis-network:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # ============= Milvus Vector Database - CPU ONLY =============
  
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /mnt/appsdata/jarvis/milvus/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      jarvis-network:
        aliases:
          - etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - /mnt/appsdata/jarvis/milvus/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      jarvis-network:
        aliases:
          - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.6.0  # CPU version, NOT GPU
    command: ["milvus", "run", "standalone"]
    hostname: milvus
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - /mnt/appsdata/jarvis/milvus/db:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    networks:
      jarvis-network:
        aliases:
          - milvus
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    depends_on:
      - etcd
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # ============= vLLM Service - OPTIMIZED FOR 12GB GPU =============
  vllm:
    image: vllm/vllm-openai:latest
    container_name: jarvis-vllm
    hostname: vllm
    environment:
      <<: *common-variables
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_TOKEN:-}
      PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True,max_split_size_mb:128"
      CUDA_VISIBLE_DEVICES: "0"
      VLLM_USAGE_SOURCE: docker
      VLLM_WORKER_MULTIPROC_METHOD: spawn
    ports:
      - "8080:8000"
    volumes:
      - /mnt/appsdata/jarvis/models/vllm:/root/.cache/huggingface
    networks:
      jarvis-network:
        aliases:
          - vllm
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: [
      "--model", "${VLLM_MODEL:-TheBloke/Mistral-7B-Instruct-v0.2-AWQ}",
      "--max-model-len", "2048",
      "--gpu-memory-utilization", "0.5",  # Conservative for 12GB GPU
      "--quantization", "awq",
      "--dtype", "half",
      "--api-key", "${VLLM_API_KEY:-jarvis-key-123}",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--enforce-eager",
      "--max-num-batched-tokens", "1024",
      "--max-num-seqs", "2"  # Very conservative
    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # ============= JARVIS Services =============
  
  llm-service:
    image: hub.rhlab.dev/jarvis/llm:latest
    container_name: jarvis-llm
    hostname: llm-service
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      <<: *common-variables
      VLLM_HOST: vllm
      VLLM_PORT: 8000
      VLLM_API_KEY: ${VLLM_API_KEY:-jarvis-key-123}
      REDIS_HOST: redis
      MODEL_NAME: ${VLLM_MODEL:-TheBloke/Mistral-7B-Instruct-v0.2-AWQ}
    ports:
      - "8001:8001"
    volumes:
      - /mnt/appsdata/jarvis/shared:/shared
      - /mnt/appsdata/jarvis/logs/llm:/logs
    networks:
      jarvis-network:
        aliases:
          - llm-service
    depends_on:
      - vllm
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  rag-service:
    image: hub.rhlab.dev/jarvis/rag:latest
    container_name: jarvis-rag
    hostname: rag-service
    deploy:
      resources:
        limits:
          memory: 1G  # Minimal memory
        reservations:
          memory: 512M
    environment:
      <<: *common-variables
      MILVUS_HOST: milvus
      MILVUS_PORT: 19530
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-jarvis}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jarvis123}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      TRANSFORMERS_CACHE: /models/transformers
      # Force CPU for embeddings to save GPU memory
      CUDA_VISIBLE_DEVICES: ""
    ports:
      - "8002:8002"
    volumes:
      - /mnt/appsdata/jarvis/shared:/shared
      - /mnt/appsdata/jarvis/documents:/documents
      - /mnt/appsdata/jarvis/models/transformers:/models/transformers
      - /mnt/appsdata/jarvis/logs/rag:/logs
    networks:
      jarvis-network:
        aliases:
          - rag-service
    depends_on:
      - milvus
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  voice-service:
    image: hub.rhlab.dev/jarvis/voice:latest
    container_name: jarvis-voice
    hostname: voice-service
    deploy:
      resources:
        limits:
          memory: 1G  # Minimal memory
        reservations:
          memory: 512M
    environment:
      <<: *common-variables
      WHISPER_MODEL: ${WHISPER_MODEL:-tiny.en}  # Smallest model
      TTS_MODEL: ${TTS_MODEL:-tts_models/en/ljspeech/tacotron2-DDC}
      FORCE_CPU: "true"  # Force CPU to save GPU
      WHISPER_CACHE: /models/whisper
      TTS_CACHE: /models/tts
    ports:
      - "8003:8003"
    volumes:
      - /mnt/appsdata/jarvis/models/whisper:/models/whisper
      - /mnt/appsdata/jarvis/models/tts:/models/tts
      - /mnt/appsdata/jarvis/shared:/shared
      - /mnt/appsdata/jarvis/logs/voice:/logs
    networks:
      jarvis-network:
        aliases:
          - voice-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  orchestrator:
    image: hub.rhlab.dev/jarvis/orchestrator:latest
    container_name: jarvis-orchestrator
    hostname: orchestrator
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      <<: *common-variables
      LLM_SERVICE_URL: http://llm-service:8001
      RAG_SERVICE_URL: http://rag-service:8002
      VOICE_SERVICE_URL: http://voice-service:8003
      VLLM_URL: http://vllm:8000
      VLLM_API_KEY: ${VLLM_API_KEY:-jarvis-key-123}
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-jarvis}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jarvis123}
      MODEL_NAME: ${VLLM_MODEL:-TheBloke/Mistral-7B-Instruct-v0.2-AWQ}
    ports:
      - "8000:8000"
    volumes:
      - /mnt/appsdata/jarvis/shared:/shared
      - /mnt/appsdata/jarvis/logs/orchestrator:/logs
    networks:
      jarvis-network:
        aliases:
          - orchestrator
    depends_on:
      - llm-service
      - rag-service
      - voice-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  web:
    image: hub.rhlab.dev/jarvis/web:latest
    container_name: jarvis-web
    hostname: web
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      <<: *common-variables
    ports:
      - "3000:80"
    volumes:
      - /mnt/appsdata/jarvis/logs/nginx:/var/log/nginx
    networks:
      jarvis-network:
        aliases:
          - web
    depends_on:
      - orchestrator
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
