global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'llm-service'
    static_configs:
      - targets: ['llm-service:8001']
    metrics_path: '/metrics'
  
  - job_name: 'rag-service'
    static_configs:
      - targets: ['rag-service:8002']
    metrics_path: '/metrics'
  
  - job_name: 'voice-service'
    static_configs:
      - targets: ['voice-service:8003']
    metrics_path: '/metrics'
  
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8000']
    metrics_path: '/metrics'
