debug: false
log_level: INFO

service:
  http_port: 6333
  grpc_port: 6334
  host: 0.0.0.0
  max_request_size_mb: 32
  max_workers: 0
  enable_cors: true

storage:
  storage_path: /qdrant/storage
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0
  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 0
    max_segment_size_kb: 200000
    memmap_threshold_kb: 50000
    flush_interval_sec: 5
    max_optimization_threads: 2
  hnsw_index:
    m: 16
    ef_construct: 100
    on_disk: false
  performance:
    max_search_threads: 0
    max_optimize_threads: 2

telemetry:
  disabled: true
